# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detailmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('uid', models.IntegerField()),
                ('contact_uid', models.IntegerField()),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_type', models.CharField(max_length=30)),
                ('message_dtm', models.DateField()),
                ('message_uid', models.IntegerField()),
                ('message_cuid', models.IntegerField()),
                ('message_dir', models.CharField(max_length=30)),
                ('message_type', models.CharField(max_length=30)),
                ('message_body', models.TextField(max_length=30)),
                ('ack', models.CharField(max_length=30)),
            ],
        ),
    ]
